-- ============================================================================
-- Ontology Metadata Tables Template
-- Replace {DATABASE}, {SCHEMA}, {ONTOLOGY_NAME} with actual values
-- ============================================================================

USE SCHEMA {DATABASE}.{SCHEMA};

-- ONT_CLASS: Ontology class hierarchy
CREATE TABLE IF NOT EXISTS ONT_CLASS (
    CLASS_NAME          STRING NOT NULL PRIMARY KEY,
    PARENT_CLASS_NAME   STRING,
    IS_ABSTRACT         BOOLEAN DEFAULT FALSE,
    DESCRIPTION         STRING,
    ONTOLOGY_NAME       STRING DEFAULT '{ONTOLOGY_NAME}',
    TYPE_CLASS          STRING DEFAULT 'ANALYTICAL',
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ONT_RELATION_DEF: Relationship definitions
CREATE TABLE IF NOT EXISTS ONT_RELATION_DEF (
    REL_NAME            STRING NOT NULL PRIMARY KEY,
    DOMAIN_CLASS        STRING NOT NULL,
    RANGE_CLASS         STRING NOT NULL,
    CARDINALITY         STRING DEFAULT 'N:N',
    IS_HIERARCHICAL     BOOLEAN DEFAULT FALSE,
    IS_TRANSITIVE       BOOLEAN DEFAULT FALSE,
    INVERSE_REL_NAME    STRING,
    DESCRIPTION         STRING,
    ONTOLOGY_NAME       STRING DEFAULT '{ONTOLOGY_NAME}',
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ONT_CLASS_MAP: Map ontology classes to physical tables
CREATE TABLE IF NOT EXISTS ONT_CLASS_MAP (
    MAP_ID              STRING DEFAULT UUID_STRING() PRIMARY KEY,
    CLASS_NAME          STRING NOT NULL,
    SOURCE_DATABASE     STRING NOT NULL,
    SOURCE_SCHEMA       STRING NOT NULL,
    SOURCE_TABLE        STRING NOT NULL,
    FILTER_COL          STRING,
    FILTER_VAL          STRING,
    ID_EXPR             STRING NOT NULL,
    NAME_EXPR           STRING,
    SUBTYPE_EXPR        STRING,
    PROPS_EXPR          STRING,
    ONTOLOGY_NAME       STRING DEFAULT '{ONTOLOGY_NAME}',
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (CLASS_NAME) REFERENCES ONT_CLASS(CLASS_NAME)
);

-- ONT_REL_MAP: Map relationships to physical edge sources
CREATE TABLE IF NOT EXISTS ONT_REL_MAP (
    MAP_ID              STRING DEFAULT UUID_STRING() PRIMARY KEY,
    REL_NAME            STRING NOT NULL,
    SOURCE_DATABASE     STRING NOT NULL,
    SOURCE_SCHEMA       STRING NOT NULL,
    SOURCE_TABLE        STRING NOT NULL,
    SRC_ID_EXPR         STRING NOT NULL,
    DST_ID_EXPR         STRING NOT NULL,
    FILTER_COL          STRING,
    FILTER_VAL          STRING,
    WEIGHT_EXPR         STRING DEFAULT '1.0',
    PROPS_EXPR          STRING,
    ONTOLOGY_NAME       STRING DEFAULT '{ONTOLOGY_NAME}',
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (REL_NAME) REFERENCES ONT_RELATION_DEF(REL_NAME)
);

-- ONT_PROPERTY: Shared properties across classes
CREATE TABLE IF NOT EXISTS ONT_PROPERTY (
    PROPERTY_NAME       STRING NOT NULL,
    CLASS_NAME          STRING NOT NULL,
    DATA_TYPE           STRING DEFAULT 'STRING',
    IS_REQUIRED         BOOLEAN DEFAULT FALSE,
    DESCRIPTION         STRING,
    SOURCE_EXPR         STRING,
    ONTOLOGY_NAME       STRING DEFAULT '{ONTOLOGY_NAME}',
    PRIMARY KEY (PROPERTY_NAME, CLASS_NAME)
);
